version: "3.8"

services:
  frontend:
    build: .
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "${PORT:-8000}:8000"
    command: npm run build && serve -s build -l 8000
    restart: always
