version: "3.8"

services:
  frontend:
    build: .
    working_dir: /src
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "${PORT:-8000}:8000"
    command: npm start --host 0.0.0.0
    restart: always
