version: "3.8"

services:
  frontend:
    build: .
    working_dir: /src
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "${PORT:-8000}:5173"
    command: npm start -- --host 0.0.0.0 --port 5173
    restart: always
