services:
  app:
    build:
      context: .
      args:
        REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
        REACT_APP_SUPABASE_ANON_KEY: ${REACT_APP_SUPABASE_ANON_KEY}
    image: git.06222001.xyz/keannu125/ecemonitoringsystem:latest
    env_file: .env
    ports:
      - "${PORT:-8000}:80"
